# Generated by Django 5.2.4 on 2025-07-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('planification', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(choices=[('no_response', 'Sans réponse'), ('happy', 'Content'), ('unhappy', 'Pas content'), ('neutral', 'Neutre')], max_length=20, unique=True, verbose_name="Type d'humeur")),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Nombre de fois sélectionnée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Compteur d'humeur",
                'verbose_name_plural': "Compteurs d'humeur",
                'ordering': ['mood_type'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Permissif, Dégradé, Maintenance', max_length=50, unique=True, verbose_name='Nom du mode')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du mode et de ses implications', verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=False, help_text='Indique si ce mode est actuellement activé', verbose_name='Activé')),
                ('is_active', models.BooleanField(default=True, help_text='Mode disponible dans le système', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de fonctionnement',
                'verbose_name_plural': 'Modes de fonctionnement',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_enabled', 'is_active'], name='wcm_mode_is_enab_366d70_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict, help_text="Format: {item_id: 'ok'/'nok'/'na'}", verbose_name='Réponses')),
                ('operator_signature', models.CharField(blank=True, help_text="Initiales de l'opérateur", max_length=255, verbose_name='Signature opérateur (initiales)')),
                ('operator_signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Date signature opérateur')),
                ('management_visa', models.CharField(blank=True, help_text='Visa du responsable ayant validé la checklist', max_length=100, verbose_name='Visa management')),
                ('management_visa_date', models.DateTimeField(blank=True, null=True, verbose_name='Date visa management')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to='planification.operator', verbose_name='Opérateur')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_response', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Réponse check-list',
                'verbose_name_plural': 'Réponses check-list',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shift'], name='wcm_checkli_shift_i_884922_idx')],
            },
        ),
        migrations.CreateModel(
            name='LostTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Clé de session pour lier au shift en cours', max_length=255, null=True)),
                ('motif', models.CharField(blank=True, help_text="Motif d'arrêt en texte libre (déprécié)", max_length=100, verbose_name='Motif (texte libre)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('duration', models.PositiveIntegerField(help_text="Durée de l'arrêt en minutes", verbose_name='Durée (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planification.operator', verbose_name='Créé par')),
                ('reason', models.ForeignKey(blank=True, help_text="Motif de l'arrêt depuis le catalogue", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.wcmlosttimereason', verbose_name='Motif')),
                ('shift', models.ForeignKey(blank=True, help_text='Poste associé (si déjà sauvegardé)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_time_entries', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': "Temps d'arrêt",
                'verbose_name_plural': "Temps d'arrêt",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shift', '-created_at'], name='wcm_losttim_shift_i_0e5d6c_idx'), models.Index(fields=['session_key', '-created_at'], name='wcm_losttim_session_65f694_idx'), models.Index(fields=['reason', '-created_at'], name='wcm_losttim_reason__c1fb4e_idx')],
            },
        ),
    ]
