# Generated by Django 5.2.4 on 2025-07-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planification', '0001_initial'),
        ('production', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(choices=[('no_response', 'Sans réponse'), ('happy', 'Content'), ('unhappy', 'Pas content'), ('neutral', 'Neutre')], max_length=20, unique=True, verbose_name="Type d'humeur")),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Nombre de fois sélectionnée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Compteur d'humeur",
                'verbose_name_plural': "Compteurs d'humeur",
                'ordering': ['mood_type'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, help_text='Description du template et de son usage', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de check-list',
                'verbose_name_plural': 'Templates de check-list',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='wcm_checkli_is_acti_ef387c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Question ou point à vérifier', max_length=200, verbose_name="Texte de l'item")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=True, help_text='Cet item doit-il obligatoirement être complété?', verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wcm.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item de check-list',
                'verbose_name_plural': 'Items de check-list',
                'ordering': ['template', 'order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='LostTimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Code unique (généré automatiquement si vide)', max_length=10, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du motif')),
                ('category', models.CharField(blank=True, choices=[('arret_programme', 'Arrêt programmé'), ('panne', 'Panne'), ('changement_serie', 'Changement de série'), ('reglage', 'Réglage'), ('maintenance', 'Maintenance'), ('qualite', 'Problème qualité'), ('approvisionnement', 'Approvisionnement'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_planned', models.BooleanField(default=False, help_text="Indique si c'est un arrêt planifié", verbose_name='Arrêt planifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('color', models.CharField(default='#6c757d', help_text="Couleur pour l'affichage dans l'interface", max_length=7, verbose_name='Couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motif de temps perdu',
                'verbose_name_plural': 'Motifs de temps perdus',
                'ordering': ['category', 'order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='wcm_losttim_is_acti_a7717a_idx'), models.Index(fields=['code'], name='wcm_losttim_code_4dcee0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LostTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Clé de session pour lier au shift en cours', max_length=255, null=True)),
                ('motif', models.CharField(blank=True, help_text="Motif d'arrêt en texte libre (déprécié)", max_length=100, verbose_name='Motif (texte libre)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('duration', models.PositiveIntegerField(help_text="Durée de l'arrêt en minutes", verbose_name='Durée (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planification.operator', verbose_name='Créé par')),
                ('shift', models.ForeignKey(blank=True, help_text='Poste associé (si déjà sauvegardé)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_time_entries', to='production.shift', verbose_name='Poste')),
                ('reason', models.ForeignKey(blank=True, help_text="Motif de l'arrêt depuis le catalogue", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wcm.losttimereason', verbose_name='Motif')),
            ],
            options={
                'verbose_name': "Temps d'arrêt",
                'verbose_name_plural': "Temps d'arrêt",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom ou profil des paramètres machine', max_length=100, unique=True, verbose_name='Nom du profil')),
                ('oxygen_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit oxygène primaire', max_digits=6, null=True, verbose_name='Oxygène primaire')),
                ('oxygen_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit oxygène secondaire', max_digits=6, null=True, verbose_name='Oxygène secondaire')),
                ('propane_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit propane primaire', max_digits=6, null=True, verbose_name='Propane primaire')),
                ('propane_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit propane secondaire', max_digits=6, null=True, verbose_name='Propane secondaire')),
                ('speed_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse primaire', max_digits=6, null=True, verbose_name='Vitesse primaire')),
                ('speed_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse secondaire', max_digits=6, null=True, verbose_name='Vitesse secondaire')),
                ('belt_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse du tapis en m/h', max_digits=6, null=True, verbose_name='Vitesse tapis')),
                ('is_active', models.BooleanField(default=True, help_text='Profil actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres machine',
                'verbose_name_plural': 'Paramètres machine',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='wcm_machine_is_acti_3a1616_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineParametersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Nom du paramètre')),
                ('parameter_type', models.CharField(choices=[('oxygen_primary', 'Oxygène primaire'), ('oxygen_secondary', 'Oxygène secondaire'), ('propane_primary', 'Propane primaire'), ('propane_secondary', 'Propane secondaire'), ('speed_primary', 'Vitesse primaire'), ('speed_secondary', 'Vitesse secondaire'), ('belt_speed', 'Vitesse tapis')], max_length=50, verbose_name='Type de paramètre')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nouvelle valeur')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure de modification')),
                ('machine_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcm.machineparameters', verbose_name='Paramètres machine')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planification.operator', verbose_name='Modifié par')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_parameters_history', to='production.shift', verbose_name='Poste en cours')),
            ],
            options={
                'verbose_name': 'Historique paramètres machine',
                'verbose_name_plural': 'Historiques paramètres machine',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Permissif, Dégradé, Maintenance', max_length=50, unique=True, verbose_name='Nom du mode')),
                ('code', models.SlugField(default='mode', help_text='Code technique du mode (ex: permissive, degraded)', unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du mode et de ses implications', verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=False, help_text='Indique si ce mode est actuellement activé', verbose_name='Activé')),
                ('is_active', models.BooleanField(default=True, help_text='Mode disponible dans le système', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de fonctionnement',
                'verbose_name_plural': 'Modes de fonctionnement',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_enabled', 'is_active'], name='wcm_mode_is_enab_366d70_idx'), models.Index(fields=['code'], name='wcm_mode_code_9b1db7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 80g/m², 40g/m²', max_length=50, unique=True, verbose_name='Nom du profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Profil par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_parameters', models.ForeignKey(blank=True, help_text='Paramètres machine associés à ce profil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='wcm.machineparameters', verbose_name='Paramètres machine')),
                ('specifications', models.ManyToManyField(blank=True, help_text='Spécifications qualité associées à ce profil', related_name='profiles', to='quality.specification', verbose_name='Spécifications')),
            ],
            options={
                'verbose_name': 'Profil de production',
                'verbose_name_plural': 'Profils de production',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('ok', 'OK'), ('na', 'N/A'), ('nok', 'NOK')], max_length=3, verbose_name='Réponse')),
                ('comment', models.TextField(blank=True, help_text='Commentaire optionnel, obligatoire si NOK', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcm.checklistitem', verbose_name='Item de check-list')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planification.operator', verbose_name='Répondu par')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Réponse check-list',
                'verbose_name_plural': 'Réponses check-list',
                'ordering': ['shift', 'item__order'],
                'indexes': [models.Index(fields=['shift', 'response'], name='wcm_checkli_shift_i_07b73d_idx'), models.Index(fields=['item', 'response'], name='wcm_checkli_item_id_843c4c_idx')],
                'unique_together': {('shift', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['template', 'is_active'], name='wcm_checkli_templat_069840_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='losttimeentry',
            index=models.Index(fields=['shift', '-created_at'], name='wcm_losttim_shift_i_0e5d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='losttimeentry',
            index=models.Index(fields=['session_key', '-created_at'], name='wcm_losttim_session_65f694_idx'),
        ),
        migrations.AddIndex(
            model_name='losttimeentry',
            index=models.Index(fields=['reason', '-created_at'], name='wcm_losttim_reason__c1fb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='machineparametershistory',
            index=models.Index(fields=['-timestamp'], name='wcm_machine_timesta_a2fc11_idx'),
        ),
        migrations.AddIndex(
            model_name='machineparametershistory',
            index=models.Index(fields=['shift', '-timestamp'], name='wcm_machine_shift_i_156aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='machineparametershistory',
            index=models.Index(fields=['parameter_type', '-timestamp'], name='wcm_machine_paramet_46c75f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'name'], name='wcm_profile_is_acti_a34a57_idx'),
        ),
    ]
