# Generated by Django 5.2.4 on 2025-07-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('wcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DurationField(help_text='Temps total entre début et fin du poste', verbose_name="Temps d'ouverture")),
                ('availability_time', models.DurationField(help_text="Temps d'ouverture - Temps perdu", verbose_name='Temps disponible')),
                ('lost_time', models.DurationField(help_text="Somme des temps d'arrêt", verbose_name='Temps perdu')),
                ('total_length', models.DecimalField(decimal_places=2, help_text='Longueur totale produite', max_digits=10, verbose_name='Longueur totale (m)')),
                ('ok_length', models.DecimalField(decimal_places=2, help_text='Longueur de production conforme', max_digits=10, verbose_name='Longueur conforme (m)')),
                ('nok_length', models.DecimalField(decimal_places=2, help_text='Longueur de production non conforme', max_digits=10, verbose_name='Longueur non conforme (m)')),
                ('raw_waste_length', models.DecimalField(decimal_places=2, default=0, help_text='Longueur de déchet brut', max_digits=10, verbose_name='Déchet brut (m)')),
                ('trs_percentage', models.DecimalField(decimal_places=1, help_text='Taux de Rendement Synthétique (OEE)', max_digits=5, verbose_name='TRS (%)')),
                ('availability_percentage', models.DecimalField(decimal_places=1, help_text="(Temps disponible / Temps d'ouverture) × 100", max_digits=5, verbose_name='Disponibilité (%)')),
                ('performance_percentage', models.DecimalField(decimal_places=1, help_text='(Production réelle / Production théorique) × 100', max_digits=5, verbose_name='Performance (%)')),
                ('quality_percentage', models.DecimalField(decimal_places=1, help_text='(Longueur OK / Longueur totale) × 100', max_digits=5, verbose_name='Qualité (%)')),
                ('theoretical_production', models.DecimalField(decimal_places=2, help_text='Temps disponible × Vitesse tapis', max_digits=10, verbose_name='Production théorique (m)')),
                ('profile_name', models.CharField(help_text='Nom du profil de production utilisé', max_length=100, verbose_name='Profil utilisé')),
                ('belt_speed_m_per_min', models.DecimalField(decimal_places=2, help_text='Vitesse tapis du profil utilisé', max_digits=8, verbose_name='Vitesse tapis (m/min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trs', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'TRS',
                'verbose_name_plural': 'TRS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shift'], name='wcm_trs_shift_i_dcddbc_idx'), models.Index(fields=['-created_at'], name='wcm_trs_created_57bc86_idx')],
            },
        ),
    ]
