# Generated by Django 5.2.4 on 2025-07-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='losttimereason',
            name='wcm_losttim_code_4dcee0_idx',
        ),
        migrations.RemoveIndex(
            model_name='mode',
            name='wcm_mode_code_9b1db7_idx',
        ),
        migrations.RemoveField(
            model_name='losttimereason',
            name='code',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='code',
        ),
    ]
