# Generated by Django 5.2.4 on 2025-07-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('planification', '0004_alter_fabricationorder_profile'),
        ('wcm', '0002_remove_losttimereason_wcm_losttim_code_4dcee0_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='template',
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.wcmchecklistitem', verbose_name='Item de check-list'),
        ),
        migrations.AlterField(
            model_name='losttimeentry',
            name='reason',
            field=models.ForeignKey(blank=True, help_text="Motif de l'arrêt depuis le catalogue", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.wcmlosttimereason', verbose_name='Motif'),
        ),
        migrations.RemoveField(
            model_name='machineparametershistory',
            name='machine_parameters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='machine_parameters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specifications',
        ),
        migrations.AddField(
            model_name='machineparametershistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.wcmprofile', verbose_name='Profil utilisé'),
        ),
        migrations.DeleteModel(
            name='ChecklistTemplate',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='LostTimeReason',
        ),
        migrations.DeleteModel(
            name='MachineParameters',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
