# Generated by Django 5.2.4 on 2025-07-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_paramtype_spectype_and_more'),
        ('wcm', '0003_alter_checklistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machineparametershistory',
            new_name='wcm_machine_paramet_11cf68_idx',
            old_name='wcm_machine_paramet_46c75f_idx',
        ),
        migrations.RemoveField(
            model_name='machineparametershistory',
            name='parameter_name',
        ),
        migrations.AlterField(
            model_name='machineparametershistory',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.paramtype', verbose_name='Type de paramètre'),
        ),
    ]
