# Generated by Django 5.2.4 on 2025-07-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0004_rename_wcm_machine_paramet_46c75f_idx_wcm_machine_paramet_11cf68_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineParametersHistory',
        ),
    ]
