# Generated by Django 5.2.4 on 2025-07-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0005_delete_machineparametershistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistresponse',
            options={'ordering': ['shift', 'item'], 'verbose_name': 'Réponse check-list', 'verbose_name_plural': 'Réponses check-list'},
        ),
    ]
