# Generated by Django 5.2.4 on 2025-07-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_add_wound_length_end_temp'),
        ('wcm', '0006_alter_checklistresponse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réponse check-list', 'verbose_name_plural': 'Réponses check-list'},
        ),
        migrations.RemoveIndex(
            model_name='checklistresponse',
            name='wcm_checkli_shift_i_07b73d_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklistresponse',
            name='wcm_checkli_item_id_843c4c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='checklistresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='management_visa',
            field=models.CharField(blank=True, help_text='Visa du responsable ayant validé la checklist', max_length=100, verbose_name='Visa management'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='management_visa_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date visa management'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='operator_signature',
            field=models.CharField(blank=True, help_text="Nom complet de l'opérateur ayant signé la checklist", max_length=255, verbose_name='Signature opérateur'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='operator_signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date signature opérateur'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='responses',
            field=models.JSONField(default=dict, help_text="Format: {item_id: 'ok'/'nok'/'na'}", verbose_name='Réponses'),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_response', to='production.shift', verbose_name='Poste'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['shift'], name='wcm_checkli_shift_i_884922_idx'),
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='response',
        ),
    ]
