# Generated by Django 5.2.4 on 2025-07-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0005_remove_fabricationorder_planificati_profile_beb9de_idx_and_more'),
        ('wcm', '0007_refactor_checklist_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to='planification.operator', verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='operator_signature',
            field=models.CharField(blank=True, help_text="Initiales de l'opérateur", max_length=255, verbose_name='Signature opérateur (initiales)'),
        ),
    ]
