# Generated by Django 5.2.4 on 2025-07-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profiletemplate_param_items_and_more'),
        ('production', '0002_alter_roll_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now=True, verbose_name='Sélectionné le')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profiletemplate', verbose_name='Profil actuel')),
            ],
            options={
                'verbose_name': 'Profil actuel',
                'verbose_name_plural': 'Profils actuels',
            },
        ),
    ]
