# Generated by Django 5.2.4 on 2025-07-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_currentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Rouleau'),
        ),
    ]
