# Generated by Django 5.2.4 on 2025-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_make_roll_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='wound_length_end',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Longueur enroulée fin (temporaire)'),
        ),
    ]
