# Generated by Django 5.2.4 on 2025-07-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text="Numéro d'ordre de fabrication (ex: OF12345)", max_length=50, unique=True, verbose_name="Numéro d'OF")),
                ('required_length', models.DecimalField(decimal_places=2, default=0, help_text='Longueur totale à produire - 0 = illimité', max_digits=10, verbose_name='Longueur à produire (m)')),
                ('target_roll_length', models.DecimalField(decimal_places=2, default=0, help_text='Longueur souhaitée par rouleau - 0 = illimité', max_digits=10, verbose_name='Longueur par rouleau (m)')),
                ('for_cutting', models.BooleanField(default=False, help_text='Indique si cet OF est destiné à la découpe', verbose_name='Pour la découpe')),
                ('terminated', models.BooleanField(default=False, help_text='Indique si cet OF est terminé', verbose_name='Terminé')),
                ('creation_date', models.DateField(auto_now_add=True, help_text="Date de création de l'OF", verbose_name='Date de création')),
                ('due_date', models.DateField(blank=True, help_text="Date d'échéance (optionnelle)", null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordre de Fabrication',
                'verbose_name_plural': 'Ordres de Fabrication',
                'ordering': ['-creation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Prénom de l'opérateur", max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(help_text="Nom de famille de l'opérateur", max_length=50, verbose_name='Nom')),
                ('employee_id', models.CharField(blank=True, help_text='Matricule employé (généré automatiquement si non fourni)', max_length=20, null=True, unique=True, verbose_name='Matricule')),
                ('training_completed', models.BooleanField(default=False, help_text="Indique si l'opérateur a terminé sa formation", verbose_name='Formation complétée')),
                ('is_active', models.BooleanField(default=True, help_text='Opérateur actif dans le système', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
