# Generated by Django 5.2.4 on 2025-07-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planification', '0001_initial'),
        ('wcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationorder',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profil définissant les paramètres et spécifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrication_orders', to='wcm.profile', verbose_name='Profil de production'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['is_active', 'last_name'], name='planificati_is_acti_822adf_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['employee_id'], name='planificati_employe_bb4f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricationorder',
            index=models.Index(fields=['terminated', '-creation_date'], name='planificati_termina_4b4638_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricationorder',
            index=models.Index(fields=['order_number'], name='planificati_order_n_ff74d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricationorder',
            index=models.Index(fields=['profile', '-creation_date'], name='planificati_profile_beb9de_idx'),
        ),
    ]
