# Generated by Django 5.2.4 on 2025-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricationorder',
            name='required_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur totale à produire - vide = illimité', max_digits=10, null=True, verbose_name='Longueur à produire (m)'),
        ),
        migrations.AlterField(
            model_name='fabricationorder',
            name='target_roll_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur souhaitée par rouleau - vide = illimité', max_digits=10, null=True, verbose_name='Longueur par rouleau (m)'),
        ),
    ]
