# Generated by Django 5.2.4 on 2025-07-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('planification', '0003_alter_fabricationorder_required_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricationorder',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profil définissant les paramètres et spécifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrication_orders', to='catalog.wcmprofile', verbose_name='Profil de production'),
        ),
    ]
