# Generated by Django 5.2.4 on 2025-07-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0004_alter_fabricationorder_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fabricationorder',
            name='planificati_profile_beb9de_idx',
        ),
        migrations.RemoveField(
            model_name='fabricationorder',
            name='profile',
        ),
    ]
