# Generated by Django 5.2.4 on 2025-07-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['spec_type'], 'verbose_name': 'Spécification', 'verbose_name_plural': 'Spécifications'},
        ),
        migrations.RemoveIndex(
            model_name='specification',
            name='quality_spe_name_4e5b80_idx',
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
    ]
