# Generated by Django 5.2.4 on 2025-07-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('quality', '0002_alter_specification_options_and_more'),
        ('wcm', '0003_alter_checklistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolldefect',
            name='defect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='catalog.qualitydefecttype', verbose_name='Type de défaut'),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.DeleteModel(
            name='DefectType',
        ),
    ]
