# Generated by Django 5.2.4 on 2025-07-23 17:39

from django.db import migrations, models


def convert_positions(apps, schema_editor):
    """Convertit les anciennes positions vers les nouvelles."""
    RollDefect = apps.get_model('quality', 'RollDefect')
    
    # Mapping des anciennes valeurs vers les nouvelles
    position_mapping = {
        'left': 'GC',     # Gauche → Gauche Centre par défaut
        'center': 'DC',   # Centre → Droite Centre par défaut
        'right': 'DD',    # Droite → Droite Droite par défaut
    }
    
    for defect in RollDefect.objects.all():
        if defect.side_position in position_mapping:
            defect.side_position = position_mapping[defect.side_position]
            defect.save()


def reverse_positions(apps, schema_editor):
    """Revient aux anciennes positions."""
    RollDefect = apps.get_model('quality', 'RollDefect')
    
    # Mapping inverse
    position_mapping = {
        'GG': 'left',
        'GC': 'left',
        'GD': 'left',
        'DG': 'right',
        'DC': 'center',
        'DD': 'right',
    }
    
    for defect in RollDefect.objects.all():
        if defect.side_position in position_mapping:
            defect.side_position = position_mapping[defect.side_position]
            defect.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_alter_rolldefect_defect_type_delete_specification_and_more'),
    ]

    operations = [
        # D'abord convertir les données existantes
        migrations.RunPython(convert_positions, reverse_positions),
        
        # Ensuite modifier le champ avec les nouvelles valeurs
        migrations.AlterField(
            model_name='rolldefect',
            name='side_position',
            field=models.CharField(choices=[('GG', 'Gauche Gauche'), ('GC', 'Gauche Centre'), ('GD', 'Gauche Droite'), ('DG', 'Droite Gauche'), ('DC', 'Droite Centre'), ('DD', 'Droite Droite')], help_text='Position transversale du défaut sur la laize', max_length=10, verbose_name='Position transversale'),
        ),
    ]
