# Generated by Django 5.2.4 on 2025-07-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du défaut')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du défaut', verbose_name='Description')),
                ('severity', models.CharField(choices=[('non_blocking', 'Non bloquant'), ('blocking', 'Bloquant'), ('threshold', 'Bloquant selon seuil')], help_text='Niveau de criticité du défaut', max_length=20, verbose_name='Criticité')),
                ('threshold_value', models.PositiveIntegerField(blank=True, help_text='Nombre max avant blocage (si criticité=threshold)', null=True, verbose_name='Valeur seuil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de défaut qualité',
                'verbose_name_plural': 'Types de défauts qualité',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='catalog_qua_is_acti_2f35f1_idx'), models.Index(fields=['name'], name='catalog_qua_name_20c085_idx')],
            },
        ),
        migrations.CreateModel(
            name='WcmChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, help_text='Description du template et de son usage', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de check-list WCM',
                'verbose_name_plural': 'Templates de check-list WCM',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='catalog_wcm_is_acti_d27136_idx')],
            },
        ),
        migrations.CreateModel(
            name='WcmLostTimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du motif')),
                ('category', models.CharField(blank=True, choices=[('arret_programme', 'Arrêt programmé'), ('panne', 'Panne'), ('changement_serie', 'Changement de série'), ('reglage', 'Réglage'), ('maintenance', 'Maintenance'), ('qualite', 'Problème qualité'), ('approvisionnement', 'Approvisionnement'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_planned', models.BooleanField(default=False, help_text="Indique si c'est un arrêt planifié", verbose_name='Arrêt planifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('color', models.CharField(default='#6c757d', help_text="Couleur pour l'affichage dans l'interface", max_length=7, verbose_name='Couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motif de temps perdu WCM',
                'verbose_name_plural': 'Motifs de temps perdus WCM',
                'ordering': ['category', 'order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='catalog_wcm_is_acti_4de765_idx')],
            },
        ),
        migrations.CreateModel(
            name='WcmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 80g/m², 40g/m²', max_length=50, unique=True, verbose_name='Nom du profil')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Profil par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil de production WCM',
                'verbose_name_plural': 'Profils de production WCM',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalog_wcm_is_acti_3f4073_idx')],
            },
        ),
        migrations.CreateModel(
            name='WcmChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Question ou point à vérifier', max_length=200, verbose_name="Texte de l'item")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=True, help_text='Cet item doit-il obligatoirement être complété?', verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.wcmchecklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item de check-list WCM',
                'verbose_name_plural': 'Items de check-list WCM',
                'ordering': ['template', 'order', 'text'],
                'indexes': [models.Index(fields=['template', 'is_active'], name='catalog_wcm_templat_5cd34c_idx')],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WcmProfileMachineParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(choices=[('oxygen_primary', 'Oxygène primaire'), ('oxygen_secondary', 'Oxygène secondaire'), ('propane_primary', 'Propane primaire'), ('propane_secondary', 'Propane secondaire'), ('speed_primary', 'Vitesse primaire'), ('speed_secondary', 'Vitesse secondaire'), ('belt_speed', 'Vitesse tapis')], max_length=50, verbose_name='Type de paramètre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, help_text='Unité de mesure', max_length=20, verbose_name='Unité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_params', to='catalog.wcmprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Paramètre machine de profil WCM',
                'verbose_name_plural': 'Paramètres machine de profil WCM',
                'ordering': ['profile', 'param_type'],
                'unique_together': {('profile', 'param_type')},
            },
        ),
        migrations.CreateModel(
            name='WcmProfileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('thickness', 'Épaisseur'), ('micrometer', 'Micronnaire'), ('surface_mass', 'Masse surfacique (g/25cm²)'), ('dry_extract', 'Extrait sec'), ('global_surface_mass', 'Masse surfacique globale (g/m²)')], max_length=20, verbose_name='Type de spécification')),
                ('value_min', models.DecimalField(blank=True, decimal_places=6, help_text='Seuil minimum critique', max_digits=12, null=True, verbose_name='Valeur minimale')),
                ('value_min_alert', models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte bas", max_digits=12, null=True, verbose_name='Alerte minimale')),
                ('value_nominal', models.DecimalField(decimal_places=6, help_text='Valeur cible', max_digits=12, verbose_name='Valeur nominale')),
                ('value_max_alert', models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte haut", max_digits=12, null=True, verbose_name='Alerte maximale')),
                ('value_max', models.DecimalField(blank=True, decimal_places=6, help_text='Seuil maximum critique', max_digits=12, null=True, verbose_name='Valeur maximale')),
                ('unit', models.CharField(blank=True, help_text='Unité de mesure (mm, g/m², %)', max_length=20, verbose_name='Unité')),
                ('max_nok', models.PositiveIntegerField(blank=True, help_text='Nombre max de mesures NOK consécutives avant alerte', null=True, verbose_name='Max NOK consécutifs')),
                ('is_blocking', models.BooleanField(default=False, help_text='Cette spec peut-elle bloquer la production?', verbose_name='Bloquant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.wcmprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Spécification de profil WCM',
                'verbose_name_plural': 'Spécifications de profil WCM',
                'ordering': ['profile', 'spec_type'],
                'unique_together': {('profile', 'spec_type')},
            },
        ),
    ]
