# Generated by Django 5.2.4 on 2025-07-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: oxygen_primary, belt_speed', max_length=50, unique=True, verbose_name='Nom technique')),
                ('display_name', models.CharField(help_text='Ex: Oxygène primaire, Vitesse tapis', max_length=100, verbose_name="Nom d'affichage")),
                ('category', models.CharField(choices=[('fibrage', 'Fibrage'), ('ensimeuse', 'Ensimeuse'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('unit', models.CharField(blank=True, help_text='Ex: l/min, m/h', max_length=20, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de paramètre machine',
                'verbose_name_plural': 'Types de paramètres machine',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('display_name', models.CharField(help_text='Ex: Épaisseur, Micronnaire, Masse surfacique', max_length=100, verbose_name="Nom d'affichage")),
                ('unit', models.CharField(blank=True, help_text='Ex: mm, g/m², %', max_length=20, verbose_name='Unité par défaut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de spécification',
                'verbose_name_plural': 'Types de spécifications',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='wcmprofilemachineparam',
            name='param_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.paramtype', verbose_name='Type de paramètre'),
        ),
        migrations.AlterField(
            model_name='wcmprofilespec',
            name='spec_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.spectype', verbose_name='Type de spécification'),
        ),
    ]
