# Generated by Django 5.2.4 on 2025-07-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_paramtype_spectype_and_more'),
        ('planification', '0005_remove_fabricationorder_planificati_profile_beb9de_idx_and_more'),
        ('wcm', '0005_delete_machineparametershistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcmprofilemachineparam',
            name='param_type',
        ),
        migrations.RemoveField(
            model_name='wcmprofilespec',
            name='spec_type',
        ),
        migrations.RemoveField(
            model_name='wcmprofilemachineparam',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='wcmprofilespec',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='wcmprofilemachineparam',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='wcmprofilespec',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ParamType',
        ),
        migrations.DeleteModel(
            name='SpecType',
        ),
        migrations.DeleteModel(
            name='WcmProfileMachineParam',
        ),
        migrations.DeleteModel(
            name='WcmProfile',
        ),
        migrations.DeleteModel(
            name='WcmProfileSpec',
        ),
    ]
