# Generated by Django 5.2.4 on 2025-07-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_wcmprofilemachineparam_param_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: oxygen_primary, belt_speed', max_length=50, unique=True, verbose_name='Nom technique')),
                ('display_name', models.CharField(help_text='Ex: Oxygène primaire, Vitesse tapis', max_length=100, verbose_name="Nom d'affichage")),
                ('category', models.CharField(choices=[('fibrage', 'Fibrage'), ('ensimeuse', 'Ensimeuse'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('unit', models.CharField(blank=True, help_text='Ex: l/min, m/h', max_length=20, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de paramètre machine',
                'verbose_name_plural': 'Items de paramètres machine',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: thickness, micrometer, surface_mass', max_length=50, unique=True, verbose_name='Nom technique')),
                ('display_name', models.CharField(help_text='Ex: Épaisseur, Micronnaire, Masse surfacique', max_length=100, verbose_name="Nom d'affichage")),
                ('unit', models.CharField(blank=True, help_text='Ex: mm, g/m², %', max_length=20, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de spécification',
                'verbose_name_plural': 'Items de spécification',
                'ordering': ['order', 'name'],
            },
        ),
    ]
