# Generated by Django 5.2.4 on 2025-07-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_paramitem_specitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramitem',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur par défaut pour ce paramètre', max_digits=10, verbose_name='Valeur par défaut'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='is_blocking',
            field=models.BooleanField(default=False, help_text='Cette spec peut-elle bloquer la production?', verbose_name='Bloquant'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='max_nok',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre max de mesures NOK consécutives avant alerte', null=True, verbose_name='Max NOK consécutifs'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='value_max',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Seuil maximum critique', max_digits=12, null=True, verbose_name='Valeur maximale'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='value_max_alert',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte haut", max_digits=12, null=True, verbose_name='Alerte maximale'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='value_min',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Seuil minimum critique', max_digits=12, null=True, verbose_name='Valeur minimale'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='value_min_alert',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte bas", max_digits=12, null=True, verbose_name='Alerte minimale'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='value_nominal',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Valeur cible', max_digits=12, verbose_name='Valeur nominale'),
        ),
    ]
