# Generated by Django 5.2.4 on 2025-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_paramitem_default_value_specitem_is_blocking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specitem',
            name='max_nok',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre max de mesures NOK avant blocage', null=True, verbose_name='Max NOK'),
        ),
    ]
