# Generated by Django 5.2.4 on 2025-07-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_specitem_max_nok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 80g/m², 40g/m²', max_length=100, unique=True, verbose_name='Nom du profil')),
                ('description', models.TextField(blank=True, help_text='Description du profil et de son usage', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Profil par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param_items', models.ManyToManyField(blank=True, help_text='Paramètres machine associés à ce profil', related_name='profile_templates', to='catalog.paramitem', verbose_name='Paramètres machine')),
                ('spec_items', models.ManyToManyField(blank=True, help_text='Spécifications associées à ce profil', related_name='profile_templates', to='catalog.specitem', verbose_name='Spécifications')),
            ],
            options={
                'verbose_name': 'Template de profil',
                'verbose_name_plural': 'Templates de profil',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='catalog_pro_is_acti_e91e32_idx')],
            },
        ),
    ]
