# Generated by Django 5.2.4 on 2025-07-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_profiletemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletemplate',
            name='param_items',
        ),
        migrations.RemoveField(
            model_name='profiletemplate',
            name='spec_items',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='is_blocking',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='max_nok',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='value_max',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='value_max_alert',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='value_min',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='value_min_alert',
        ),
        migrations.RemoveField(
            model_name='specitem',
            name='value_nominal',
        ),
        migrations.CreateModel(
            name='ProfileParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur du paramètre pour ce profil', max_digits=10, verbose_name='Valeur')),
                ('param_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.paramitem', verbose_name='Paramètre')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.profiletemplate', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Valeur de paramètre',
                'verbose_name_plural': 'Valeurs de paramètres',
                'unique_together': {('profile', 'param_item')},
            },
        ),
        migrations.CreateModel(
            name='ProfileSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_min', models.DecimalField(blank=True, decimal_places=6, help_text='Seuil minimum critique', max_digits=12, null=True, verbose_name='Valeur minimale')),
                ('value_min_alert', models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte bas", max_digits=12, null=True, verbose_name='Alerte minimale')),
                ('value_nominal', models.DecimalField(decimal_places=6, default=0, help_text='Valeur cible', max_digits=12, verbose_name='Valeur nominale')),
                ('value_max_alert', models.DecimalField(blank=True, decimal_places=6, help_text="Seuil d'alerte haut", max_digits=12, null=True, verbose_name='Alerte maximale')),
                ('value_max', models.DecimalField(blank=True, decimal_places=6, help_text='Seuil maximum critique', max_digits=12, null=True, verbose_name='Valeur maximale')),
                ('max_nok', models.PositiveIntegerField(blank=True, help_text='Nombre max de mesures NOK avant blocage', null=True, verbose_name='Max NOK')),
                ('is_blocking', models.BooleanField(default=False, help_text='Cette spec peut-elle bloquer la production?', verbose_name='Bloquant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.profiletemplate', verbose_name='Profil')),
                ('spec_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.specitem', verbose_name='Spécification')),
            ],
            options={
                'verbose_name': 'Valeur de spécification',
                'verbose_name_plural': 'Valeurs de spécification',
                'unique_together': {('profile', 'spec_item')},
            },
        ),
    ]
