# Generated by Django 5.2.4 on 2025-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_profiletemplate_param_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletemplate',
            name='param_items',
            field=models.ManyToManyField(blank=True, help_text='Paramètres machine associés à ce profil', related_name='profile_templates', through='catalog.ProfileParamValue', to='catalog.paramitem', verbose_name='Paramètres machine'),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='spec_items',
            field=models.ManyToManyField(blank=True, help_text='Spécifications associées à ce profil', related_name='profile_templates', through='catalog.ProfileSpecValue', to='catalog.specitem', verbose_name='Spécifications'),
        ),
    ]
