# Generated by Django 5.2.4 on 2025-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profiletemplate_param_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletemplate',
            name='belt_speed_m_per_minute',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse tapis convertie en m/min (calculée automatiquement)', max_digits=8, null=True, verbose_name='Vitesse tapis (m/min)'),
        ),
    ]
