# Generated by Django 5.2.4 on 2025-07-19 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_profiletemplate_belt_speed_m_per_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='WcmChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=True, help_text='Cet item doit-il obligatoirement être complété?', verbose_name='Obligatoire')),
            ],
            options={
                'verbose_name': 'Item de template',
                'verbose_name_plural': 'Items de template',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='wcmchecklistitem',
            options={'ordering': ['category', 'text'], 'verbose_name': 'Item de check-list WCM', 'verbose_name_plural': 'Items de check-list WCM'},
        ),
        migrations.RemoveIndex(
            model_name='wcmchecklistitem',
            name='catalog_wcm_templat_5cd34c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wcmchecklistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wcmchecklistitem',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Sécurité, Production, Qualité', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='wcmchecklistitem',
            name='text',
            field=models.CharField(help_text='Question ou point à vérifier', max_length=200, unique=True, verbose_name="Texte de l'item"),
        ),
        migrations.AddIndex(
            model_name='wcmchecklistitem',
            index=models.Index(fields=['is_active', 'category'], name='catalog_wcm_is_acti_388a26_idx'),
        ),
        migrations.AddField(
            model_name='wcmchecklisttemplateitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.wcmchecklistitem', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='wcmchecklisttemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.wcmchecklisttemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='wcmchecklisttemplate',
            name='items',
            field=models.ManyToManyField(related_name='templates', through='catalog.WcmChecklistTemplateItem', to='catalog.wcmchecklistitem', verbose_name='Items de la checklist'),
        ),
        migrations.RemoveField(
            model_name='wcmchecklistitem',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='wcmchecklistitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wcmchecklistitem',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='wcmchecklisttemplateitem',
            unique_together={('template', 'item'), ('template', 'order')},
        ),
    ]
