# Generated by Django 5.2.4 on 2025-07-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_migrate_checklist_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wcmchecklisttemplateitem',
            unique_together={('template', 'order')},
        ),
    ]
