# Generated by Django 5.2.4 on 2025-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_template_item_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletemplate',
            name='oee_target',
            field=models.DecimalField(decimal_places=2, default=85.0, help_text='Objectif de Taux de Rendement Synthétique (OEE) en pourcentage', max_digits=5, verbose_name='Objectif TRS (%)'),
        ),
    ]
